### PR TITLE
Python tests

### PR DESCRIPTION
**Pull request by sheridanchris**
## Proposed Changes
Add python tests that can be executed in CI through an optional build target.
You can run these tests with `./build.sh RunPythonTests`

### CODE REVIEW

**Comment by dbrattli** [comment]
This bug is fixed in Fable 4.2.2. But there's a another error now that blocks this PR:

```
ImportError: cannot import name 'start_child' from 'fable_modules.fable_library.async_'
```

I'll see if I can fix this as well but it might take some time since it requires rework of the async scheduler / trampoline to handle async parallel correctly.

**Comment by TheAngryByrd** [comment]
Thanks for looking into it!

**Comment by dbrattli** [comment]
Have a local fix, all tests are green. Need to do some more testing to check there's no other regressions, and then we need to release another Fable. 

Screenshot 2023-10-16 at 09 15 24

**Comment by TheAngryByrd** [comment]
@dbrattli Thanks for looking into all the issues! I really appreciate the work you've put into all this.

Got one more for ya. Windows builds are failing with:

```
> "python" "tests/FsToolkit.ErrorHandling.Tests\.python-tests\main.py" (In: false, Out: false, Err: false)
Traceback (most recent call last):
  File "D:\a\FsToolkit.ErrorHandling\FsToolkit.ErrorHandling\tests\FsToolkit.ErrorHandling.Tests\.python-tests\main.py", line 34, in <module>
    main(sys.argv[1:])
  File "D:\a\FsToolkit.ErrorHandling\FsToolkit.ErrorHandling\tests\FsToolkit.ErrorHandling.Tests\.python-tests\main.py", line 30, in main
    return Pyxpecto_runTests(all_tests)
  File "D:\a\FsToolkit.ErrorHandling\FsToolkit.ErrorHandling\tests\FsToolkit.ErrorHandling.Tests\.python-tests\fable_modules\fable_pyxpecto\pyxpecto.py", line 1019, in Pyxpecto_runTests
    return Pyxpecto_runViaPy(test)
  File "D:\a\FsToolkit.ErrorHandling\FsToolkit.ErrorHandling\tests\FsToolkit.ErrorHandling.Tests\.python-tests\fable_modules\fable_pyxpecto\pyxpecto.py", line 987, in Pyxpecto_runViaPy
    to_console(printf("\U0001f680 start running tests ..."))
  File "D:\a\FsToolkit.ErrorHandling\FsToolkit.ErrorHandling\tests\FsToolkit.ErrorHandling.Tests\.python-tests\fable_modules\fable_library\string_.py", line 68, in to_console
    return continue_print(print, arg)
  File "D:\a\FsToolkit.ErrorHandling\FsToolkit.ErrorHandling\tests\FsToolkit.ErrorHandling.Tests\.python-tests\fable_modules\fable_library\string_.py", line 61, in continue_print
    ret = arg.cont(cont)
  File "D:\a\FsToolkit.ErrorHandling\FsToolkit.ErrorHandling\tests\FsToolkit.ErrorHandling.Tests\.python-tests\fable_modules\fable_library\string_.py", line 199, in _
    return cont(str)
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f680' in position 0: character maps to <undefined>
Finished (Failed) 'PythonTest' in 00:00:28.5431365
```

Any ideas?

**Comment by dbrattli** [comment]
This one is a bit weird. Cannot reproduce. Not sure what the difference can be. https://github.com/fable-compiler/Fable/pull/3563

**Comment by TheAngryByrd** [comment]
> This one is a bit weird. Cannot reproduce. Not sure what the difference can be. [fable-compiler/Fable#3563](https://github.com/fable-compiler/Fable/pull/3563)

Yeah and I can't reproduce it locally on my windows box either 😢 

```
dotnet --info
.NET SDK:
 Version:   7.0.401
 Commit:    eb26aacfec

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.401\

python --version
Python 3.10.7
```

**Comment by TheAngryByrd** [comment]
```
run: |
  chcp 65001
  ./build.cmd PythonTest
env:
  PYTHONIOENCODING: utf-8
```

This seemed to have worked 🤷‍♂️

**Pull request merged**
