### PR TITLE
Add defaultError and zipError

### PR DESCRIPTION
**Pull request by sep2**

### CODE REVIEW

**Review by TheAngryByrd — CHANGES_REQUESTED** [review]
Thanks! Mind adding these to AsyncResult, TaskResult, and JobResult as well?

**Comment by sep2** [comment]
Sure, haven't use them though, will do later

**Review by sep2 — COMMENTED** [review]
added to AsyncResult/JobResult/TaskResult

**Review by TheAngryByrd — CHANGES_REQUESTED** [review]
Looks like the `zipError` tests are missing for `AsyncResult`/`TaskResult`/`JobResult`. Mind adding those too?

**Comment by sep2** [comment]
Did not find tests for `AsyncResult`/`TaskResult`/`JobResult` version `zip` as reference implementations for `zipError`, mind if I add them as well?

**Review by TheAngryByrd — APPROVED** [review]
Thank you!!!

**Pull request merged**
