### PR TITLE
Add Result.valueOr

### PR DESCRIPTION
**Pull request by cmeeren**
I think this is useful. Feel free to disagree. :)

### CODE REVIEW

**Comment by cmeeren** [comment]
Hmm. We could, but I'm not sure it makes perfect sense for a function called `defaultWith` to accept the error case. Also `Option.defaultWith` accepts a thunk; I'm not sure whether thunks semantically should always accept `unit` or if they can accept other arguments.

FSharpPlus calls this function `valueOr` (for their `Validation` type).

All of the above may be non-issues, however. I'll let you decide. :)

**Comment by TheAngryByrd** [comment]
Sounds good to me. 

Then I’d say just add two tests as well and let’s the this merged.

**Comment by cmeeren** [comment]
There. Edited directly through GH, hope there's no silly mistakes.

**Comment by demystifyfp** [comment]
Thanks, @cmeeren for the new function. Would you be able to add it in the documentation as well?

**Pull request merged**
