### PR TITLE
Benchmarks for Alternative Implementations, Inline, and InlineIfLambda

### PR DESCRIPTION
**Pull request by TheAngryByrd**
## Proposed Changes

Benchmarks for Alternative Implementations, Inline, and InlineIfLambda

InlineIfLambda [RFC](https://github.com/fsharp/fslang-design/blob/main/FSharp-6.0/FS-1098-inline-if-lambda.md) and [PR](https://github.com/dotnet/fsharp/pull/6811)

## Types of changes

What types of changes does your code introduce to MyLib.1?
_Put an `x` in the boxes that apply_

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected) I'm not sure if this exactly a breaking change but as it touches a lot of the code, I'm just going to assume a major bump.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] Build and tests pass locally
- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by TheAngryByrd** [comment]
# Benchmarks exploration (WIP)

Types of Implementations:

- Normal
  - Reuse functions, for example, apply can be implemented in terms of bind
- Alternative
  - Don't reuse functions, do the match implementation in the body

Variations for each:

- [inline](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/functions/inline-functions)
  - Which is known to give performance boosts
- [InlineIfLambda](https://github.com/fsharp/fslang-design/blob/main/FSharp-6.0/FS-1098-inline-if-lambda.md)
  - new perfomance technique if F# 6.0

I've chosen a few functions, specifically `eitherMap` and `map2` as they call into other functions typically and inlining all the match statements, using inline, and the new InlineIfLambda should give some interesting results.

And as I've benchmarked and done deep analysis, I've notices the composition operator `>>` creates a lot of code where as a lambda will produce a lot less.

- Additional variations
  - No Composition Operator

Composition doesn't apply the `Alt` implementations so it leaves us with:

- EitherMap
  - [Result Normal EitherMap](#result-normal-eithermap)
  - [Result Normal No Composition EitherMap](#result-normal-no-composition-eithermap)
  - [Result Normal Inline EitherMap](#result-normal-inline-eithermap)
  - [Result Normal Inline No Composition EitherMap](#result-normal-inline-no-composition-eithermap)
  - [Result Normal InlineIfLambda EitherMap](#result-normal-inlineiflambda-eithermap)
  - [Result Normal InlineIfLambda NoComposition EitherMap](#result-normal-inlineiflambda-no-composition-eithermap)
  - [Result Alt EitherMap](#result-alt-eithermap)
  - [Result Alt Inline EitherMap](#result-alt-inline-eithermap)
  - [Result Alt InlineIfLambda EitherMap](#result-alt-inlineiflambda-eithermap)
- Map2
  - [Result Normal EitherMap](#result-normal-map2)
  - [Result Normal No Composition EitherMap](#result-normal-no-composition-map2)
  - [Result Normal Inline EitherMap](#result-normal-inline-map2)
  - [Result Normal Inline No Composition EitherMap](#result-normal-inline-no-composition-map2)
  - [Result Normal InlineIfLambda EitherMap](#result-normal-inlineiflambda-map2)
  - [Result Normal InlineIfLambda No Composition EitherMap](#result-normal-inlineiflambda-no-composition-map2)
  - [Result Alt EitherMap](#result-alt-map2)
  - [Result Alt Inline EitherMap](#result-alt-inline-map2)
  - [Result Alt InlineIfLambda EitherMap](#result-alt-inlineiflambda-map2)

I'm going to show the benchmarks first but then explore each of these in detail below by showing the F# Code, the decompiled code in C# and any interesting findings. I've included a SharpLab link for each so you can see the code for yourself.

## Benchmark Results

### EitherMap


|                                              Method |      Mean |     Error |    StdDev | Ratio | RatioSD |  Gen 0 | Allocated |
|---------------------------------------------------- |----------:|----------:|----------:|------:|--------:|-------:|----------:|
|                             Result_Normal_EitherMap | 19.833 ns | 0.3458 ns | 0.3235 ns |  1.00 |    0.00 | 0.0057 |      48 B |
|              Result_Normal__NoComposition_EitherMap | 20.158 ns | 0.1837 ns | 0.1434 ns |  1.01 |    0.02 | 0.0057 |      48 B |
|                            Result_Inlined_EitherMap |  3.275 ns | 0.0408 ns | 0.0341 ns |  0.16 |    0.00 |      - |         - |
|              Result_Inlined_NoComposition_EitherMap |  3.237 ns | 0.0957 ns | 0.2402 ns |  0.16 |    0.01 |      - |         - |
|                      Result_InlinedLambda_EitherMap |  3.003 ns | 0.0472 ns | 0.0441 ns |  0.15 |    0.00 |      - |         - |
| Result_Normal_InilnedLambda_NoComposition_EitherMap |  3.449 ns | 0.0953 ns | 0.1904 ns |  0.18 |    0.01 |      - |         - |
|                                Result_Alt_EitherMap |  3.301 ns | 0.0908 ns | 0.1637 ns |  0.16 |    0.01 |      - |         - |
|                        Result_Alt_Inilned_EitherMap |  3.349 ns | 0.0876 ns | 0.1464 ns |  0.17 |    0.01 |      - |         - |
|                  Result_Alt_InilnedLambda_EitherMap |  3.337 ns | 0.0922 ns | 0.1488 ns |  0.17 |    0.01 |      - |         - |

### Map2


|                                  Method |      Mean |     Error |    StdDev | Ratio | RatioSD |  Gen 0 | Allocated |
|---------------------------------------- |----------:|----------:|----------:|------:|--------:|-------:|----------:|
|                      Result_Normal_Map2 | 56.549 ns | 0.8351 ns | 0.6974 ns |  1.00 |    0.00 | 0.0172 |     144 B |
|               Result_NoComposition_Map2 | 55.577 ns | 0.6339 ns | 0.5619 ns |  0.98 |    0.02 | 0.0172 |     144 B |
|                     Result_Inlined_Map2 | 23.692 ns | 0.2581 ns | 0.2414 ns |  0.42 |    0.01 | 0.0038 |      32 B |
|       Result_Inlined_NoComposition_Map2 | 23.905 ns | 0.2586 ns | 0.2292 ns |  0.42 |    0.01 | 0.0038 |      32 B |
|               Result_InlinedLambda_Map2 | 11.263 ns | 0.2560 ns | 0.6327 ns |  0.21 |    0.01 | 0.0038 |      32 B |
| Result_InlinedLambda_NoComposition_Map2 | 12.034 ns | 0.1359 ns | 0.1271 ns |  0.21 |    0.00 | 0.0038 |      32 B |
|                         Result_Alt_Map2 |  6.182 ns | 0.0666 ns | 0.0623 ns |  0.11 |    0.00 |      - |         - |
|                 Result_Alt_Inlined_Map2 |  3.108 ns | 0.0294 ns | 0.0260 ns |  0.06 |    0.00 |      - |         - |
|           Result_Alt_InlinedLambda_Map2 |  3.127 ns | 0.0437 ns | 0.0409 ns |  0.06 |    0.00 |      - |         - |
|          Result_Alt_InlinedLambda2_Map2 |  3.080 ns | 0.0250 ns | 0.0221 ns |  0.05 |    0.00 |      - |         - |

 

## Result Normal EitherMap

This is base case implementation. It doesn't try to do anything fancy, in fact it tries to [re-use](https://en.wikipedia.org/wiki/Code_reuse) existing functions so the implmentations don't vary. However as we can see, this seems to be leading to some performance issues.

[Sharplab link](https://sharplab.io/#v2:DYLgZgzgPgsAUMApgFwAQHsDWAxVAPVAXn1QGpUAmeJNRAJzvTtwOIIFpUAWalVAQwAmgkgE8iJcqPjwAtukEBXJKgBKiCMrSF4qPanlKVAOSaz+wIrv02aqRAEtkAC3oYc9hkxZW4N//rmyADGziQA7k7O1gE2UKgA8pgk7AB87iwxsXrxAKJedJ6FaUXeRTJ+sXaOLvQAsvwADhmlzCQ6ldl6Na6FABRYuKnp6prAyAB0SQCUqH30jG3DahpaE/mLs3gVhsqIqLl4/LKNSBC+tnyHx6eIAPq5UfVNc7PEWf5J3B9xI6vjE1MdHMwAmPWezUGrVw8CAA===)

### Interesting Findings (rnem)

I do find the C# decomplilation of the `Example_EitherMap` intersting as you can see it has many calls and classes it has to make to get to the actual matter at hand. By contrast in later variations, this will be less convoluted.

## Result Normal No Composition EitherMap

This is removing the `>>` (composition operator) calls.

[Sharplab link](https://sharplab.io/#v2:DYLgZgzgPgsAUMApgFwAQHsDWAxVAPVAXn1QGpUAmeJNRAJzvTtwOIIFpUAWalVAQwAmgkgE8iJcqPjwAtukEBXJKgBKiCMrSF4qPanlKVAOSaz+wIrv03DyxKlMBhdLIAO6CAEtkX9ADsrOBsQ/RpURB8AC3pUAAosbABKePpGZhTWa1Ccg35kAGMokgB3aOzckKhUAHlMEnYAPgwcfArK/WqAUQYmCIZUJv703DSZYI7UcMjkGLoAWX43eMSUuLSmZJIdCcn9Gbn4sEVAjmaCKGbE1Eu1DS0AOjq148DxIfFbjeYb5vVNYDIB49dKZcZ2FRdPD8dxICBBGzhKEwtxIAD6XWi9EWyziKWI7RsdW4hM6f3ugIepjo5mAVPQLncnh8fn8DwO2KWLVGvR+8CAA)

### Interesting Findings (rnncem)

Nothing really different from the Normal implementation.

## Result Normal Inline EitherMap

This is only adding the `inline` keyword to all functions associated with `eitherMap`.

[Sharplab link](https://sharplab.io/#v2:DYLgZgzgPgsAUMApgFwAQHsDWAxVAPVAXn1QGpUAmeJNRAJzvTtwOIIFpUAWalVAQwAmgkgE8iJcqPjwAtukEBXJKgBKiCMrSF4qPanlKVASQB2wAJanEI4ql37HNVFcvXUiC8gAW9DDg8GJhYiB0dwg35kAGNvEgB3L28wiP0oVAB5TBJ2AD5/FhTU1HSAUSC6QMq8quCqmThi51crRA8k+gBZfgAHAtrmEh1G4v1PHz8ACixcXPz1TWBkADosgEpUSfpGQbm1DS1l8p2NvAbDZTbSvH5ZHqQIUJG9Z2vb+8QAfVKOum6+yYbYhFRxZbggtLzA5LZZmNw2ZbjXx/Xr9bZ1eBAA=)


### Interesting Findings (rniem)

`Example_EitherMap` looks a lot less complicated and the performance represents that.

## Result Normal Inline No Composition EitherMap

This is adding the `inline` keyword to all functions associated with `eitherMap` and removing the `>>` (composition operator) calls.

[Sharplab link](https://sharplab.io/#v2:DYLgZgzgPgsAUMApgFwAQHsDWAxVAPVAXn1QGpUAmeJNRAJzvTtwOIIFpUAWalVAQwAmgkgE8iJcqPjwAtukEBXJKgBKiCMrSF4qPanlKVASQB2wAJanEI4ql37HNVFcvXUiC8gAW9DDg8GJhYiB0dwg35kAGNvEgB3L28wiP0oVAB5TBJ2AD5/FhTU1HSAUSC6QMq8quCqmThi51crRA8k+gBZfgAHAtrmEh1G4v1PHz8ACjBFUxz8gih8rFwltQ0tADosgEpUadnUcRrxNfpGQbX1TWBkTfKLvbwGw2U20rx+WR6kCFCRvTOD5fH6IAD6pQ6dG6fUme2IRUcWW4iLS+WuWzMbhsm3GvmhvX65zq8CAA===)

### Interesting findings (rnincem)

While there's no noticible performance gains, there's quite a bit less C# code by comparison.

## Result Normal InlineIfLambda EitherMap

This is adding the `InlineIfLambda` attribute to the function parameters.

[Sharplab link](https://sharplab.io/#v2:DYLgZgzgPgsAUMApgFwAQHsDWAxVAPVAXn1QGpUAmeJNRAJzvTtwOIIFpUAWalVAQwAmgkgE8iJcqPjwAtukEBXJKgBKiCMrSF4qPanlKVASQB2wAJanEggDL9ZAI0H8iu/R5qorl66kQWyAAW9KgAFADaADxmvojGYPZOLgB8ALoYOACU4dGxVvGJDs786f4MTNg5rO4edQb8yADGQSQA7oFBtfX6UKgA8pgk7CmZLN09qH0AohV05fMjC5ULMnCTXj4F/p30ALL8AA65MeYFCUklZVhVJ/nWF8WpGfSMzNVu65P6AcGhYTdUClRupNMBkAA6QY5MKvFbAtQaLQQ2ZvaprQzKRCoaZ4ByHJAQT6ePi4/FIAD6012dAOxzCOWIEw8g24zN6IKR4Ih9xslxcEN+IVpRzGy2YqHgQA)

### Interesting findings (rniilem)

No performance differences from `inline` and the C# code doesn't look much different either.

## Result Normal InlineIfLambda No Composition EitherMap

This is adding the `inline` keyword to all functions associated with `eitherMap`, adding the `InlineIfLambda` attribute to the function parameters and removing the `>>` (composition operator) calls.

[Sharplab link](https://sharplab.io/#v2:DYLgZgzgPgsAUMApgFwAQHsDWAxVAPVAXn1QGpUAmeJNRAJzvTtwOIIFpUAWalVAQwAmgkgE8iJcqPjwAtukEBXJKgBKiCMrSF4qPanlKVASQB2wAJanEggDL9ZAI0H8AcugDC6WQAd0EC2QLdFMiXX0ImlQrS2tURECAC3pUAAoAbQAeM1jEYzB7JxcAPgBdDBwASjSsnKs8godnfjL4hiZsatZwiN6DfmQAY0SSAHcknr79KFQAeUwSdmKKlkmp1BmAUXa6Nt2lvY69mTh1qJj6+KT6AFl+Hxrs83r8wubWrE7HuutXppLyvRGMwumFTut9AlkMldqkwIpQhxlgQoMtPhtlupNMBkAA6ebVOEI1DiA7iVGHZgYtQaLS47bAronQzKRCoTZ4Bw+JAQMGRPgcrlIAD6m2udDuD1S1WIawi824cummNpONxPxsbxc7i8vn8gWCplxUJhkpWlNw8CAA===)

### Interesting findings (rniilncem)

Again no noticible perfomance differences, however the C# code is greatly reduced and very readable compared to any of the previous variations. It doesn't seem to be generating classes and other static methods.

## Result Alt EitherMap

Instead of writing this in terms of the `either` function, this will do the `match` statement in the body of the function.

[Sharplab link](https://sharplab.io/#v2:DYLgZgzgPgsAUMApgFwAQHsDWAxVAPVAXn1QGpUAmeJNRAJzvTtwOIIFpUAWalVAQwAmgkgE8iJcqPjwAtukEBXJKgBKiCMrSF4qPanlKVAQWDbUu/VZqpEAS2QALegFl+ABww5bDJiyKWVkEG/MgAxo4kAO4OjoHB+lCoAPKYJOwAfF7+UFmp8QmoSQCivnS2qJk+jMwVuailNTJwcgrKiA14/LLuSBABcNZ8xV09SAD6xbGuHqgAFACUEgVWqdwriVnqmmYAdKbIu/ZOM55YuPQ1uEA====)

### Interesting findings (raem)

Again no noticible perfomance differences, but is making classes again.

## Result Alt Inline EitherMap

Same with the previous variation except it also includes the `inline` keyword.

[Sharplab link](https://sharplab.io/#v2:DYLgZgzgPgsAUMApgFwAQHsDWAxVAPVAXn1QGpUAmeJNRAJzvTtwOIIFpUAWalVAQwAmgkgE8iJcqPjwAtukEBXJKgBKiCMrSF4qPanlKVAQWDbUu/VcPLEqAJIA7YAEtHiEcSv7L37zVQ3V3dURBdkAAt6AFl+AAcMHFCGJhYiXz9M2X5kAGMIkgB3cIiMzO8oVAB5TBJ2AD5EtKhGmrLy/UqAURS6UNQG5MZmfpbUHuGZOBsVLrx+WTikCHS4KwC5haXEAH0ukpj41AAKAEoJdv0a7ku9MfVNMwA6U2Qnp2CPJ7DIw4SsXD0Ya4IA=)

### Interesting findings (raiem)

Again no noticible perfomance differences, but with like the [Result Normal InlineIfLambda NoComposition EitherMap], it produces simple C# code.

## Result Alt InlineIfLambda EitherMap

Same with the previous variation except it also includes the `InlineIfLambda` attribute.

[Sharplab link](https://sharplab.io/#v2:DYLgZgzgPgsAUMApgFwAQHsDWAxVAPVAXn1QGpUAmeJNRAJzvTtwOIIFpUAWalVAQwAmgkgE8iJcqPjwAtukEBXJKgBKiCMrSF4qPanlKVAQWDbUu/VcPLEqAJIA7YAEtHiQQBl+sgEaD+IksrENQaVDdXd1REF2QAC3oAWX4AB1QACgBtAB4nKMR7MG8/AIA+AF0MHABKTNz8t0Lin39+SpiGJmw6kh04UMH9WX5kAGN4kgB3OPjgoZCoVAB5TBJ2MuqWVChN1fmF/SWAUS66GNQNzsZmC93UU5uDw4s4GxVjvB9UpAgggf04U+3yQAH1jrNkmlMnViM99KtuPC9Pd1JozAA6UzIDGNdxeVoBDGxBJQ9JYXD0G64IA=)

### Interesting findings (raiilem)

Again no noticible perfomance differences, but with like the [Result Normal InlineIfLambda NoComposition EitherMap], it produces simple C# code.

**Comment by TheAngryByrd** [comment]
Given the `Alt` implementation and `InlineIfLambda` seems to give the best performance benefits, it's time to change the implementation of these functions.

**Comment by TheAngryByrd** [comment]
After reading the docs on [InlineIfLambda](https://docs.microsoft.com/en-us/dotnet/fsharp/whats-new/fsharp-6#inlineiflambda)


> An opt-in warning (/warnon:3517, off by default) can be turned on to indicate places in your code where InlineIfLambda arguments are not bound to lambda expressions at call sites. In normal situations, this warning should not be enabled. However, in certain kinds of high-performance programming, it can be useful to ensure all code is inlined and flattened.


Turning this on for the benchmarks.fsproj gives quite a few warnings. Going to keep digging at how to use this properly.

**Comment by TheAngryByrd** [comment]
```fsharp
let inline map ([<InlineIfLambda>] mapper : 'ok -> 'ok2) value  =
    match value with
    | Ok x -> Ok(mapper x)
    | Error e -> Error e


let inline bind ([<InlineIfLambda>] binder: 'ok -> Result<'ok2, 'err>) value  =
    match value with
    | Ok x -> binder x
    | Error e -> Error e
 ```
 
 > warning FS3517: The value 'mapper' was marked 'InlineIfLambda' but was not determined to have a lambda value. This warning is for informational purposes only
 >  warning FS3517: The value 'binder' was marked 'InlineIfLambda' but was not determined to have a lambda value. This warning is for informational purposes only.
 
 --- 
 
 Does this mean these implementations can't take advantage of this attribute? cc @baronfel @dsyme @mrange

**Comment by mrange** [comment]
@TheAngryByrd TBH I haven't looked closely on this but my guess is that you get this error message when you pass a function value that is not a lambda. Something like this:
```fsharp
bind x.MyBind v
```

`x.MyBind` is a function that matches the signature but is not a lambda and thus won't be inlined.

AFAICT if you provide a lambda it shouldn't give you the warning but I haven't tried.

```fsharp
bind (fun x -> doSomeStuff x) v
```

The warning seems to be generated here:
https://github.com/dotnet/fsharp/blob/edd4c3b902bb28af15460813a823346fb4c17ad3/src/fsharp/Optimizer.fs#L2754

**Comment by kerams** [comment]
This goes to show how big of a deal `InlineIfLambda` is. We get serious performance improvements while still writing clean, idiomatic F# code. Now there's even less need to resort to "imperative nonsense" :-).

Really nice work here.

**Pull request merged**
