### PR TITLE
Add ignore for a few of the types

### PR DESCRIPTION
**Pull request by CameronAavik**
This includes 8 new functions:

- `Result.ignore`
- `AsyncResult.ignore`
- `ResultOption.ignore`
- `AsyncResultOption.ignore`
- `JobResult.ignore`
- `JobResultOption.ignore`
- `TaskResult.ignore`
- `TaskResultOption.ignore`

While I was adding these I also fixed up a few incorrect function parameter names as I saw them (especially in the `JobResult` and `TaskResult` modules).

I wasn't sure how to build the gitbook, so would someone be able to clone my branch and make sure it looks good before merging?

### CODE REVIEW

**Comment by CameronAavik** [comment]
The build error is confusing, the tests are passing on my machine so I'm guessing it's something to do with how `Fable` encodes `unit option` types? I've never used Fable so not sure how to resolve this issue.

**Comment by TheAngryByrd** [comment]
Hmm interesting that Fable sometimes defines unit as undefined and sometimes as null.  I just asked about the Fable build errors in FSSF slack chat.

**Comment by CameronAavik** [comment]
Seems it will be fixed next fable release, did we want to wait for that or should I just rewrite it to not use `Option.map`?

**Comment by TheAngryByrd** [comment]
I'm.ok with waiting since fable usually releases bug fixes relatively quickly.

**Comment by TheAngryByrd** [comment]
So it looks like it's already out https://github.com/fable-compiler/Fable/releases/tag/2.4.6

Try bumping the fable-compiler version to it in the package.json

**Comment by demystifyfp** [comment]
Thanks, @CameronAavik for the pull request and @TheAngryByrd  & @cmeeren for jumping in :) Will publish the new NuGet version in few hours.

**Comment by demystifyfp** [comment]
It's up now! https://www.nuget.org/packages/FsToolkit.ErrorHandling/1.2.4

**Pull request merged**
