### PR TITLE
Borrows more Cvdm code to enhance computation expressions

### PR DESCRIPTION
**Pull request by TheAngryByrd**
More work as part of #3.

This enhances the computation expressions to be on par with Cvdm

### CODE REVIEW

**Comment by cmeeren** [comment]
🙌

**Comment by demystifyfp** [comment]
Thanks, @TheAngryByrd for the contribution.
It'd be also helpful if you can add the associated tests as well. Thanks in advance :)

@cmeeren does it cover all the CE from Cvdm?

**Comment by cmeeren** [comment]
The best way to know is to also include all the tests and see if they pass. :)

That said, `ResultBuilder.Combine` is missing (so some of the tests probably wouldn't even compile). And some methods delegate to relevant module functions already existing in this library, which they should, but I can't immediately say whether it's exactly the same.

In general though, for consistency (e.g. for consistent generic type parameter names in signatures), I'd also copy over the definitions of the members that were currently defined in this library. Alternatively, remove the type annotations (or rename generic type params) in the imported methods.

And regarding type annotations: They should probably be explicitly specified, because some places they do impact the behaviour. I vaguely remember something about `AsyncResult.Combine` allowing stuff that didn't make sense for that CE until I locked it down with annotations that prevented such stuff from compiling (though I might mix Combine with another method).

Summary, my recommendation is:
* Import *all* CE members as-is from Cvdm.ErrorHandling, including type annotations
* Import all CE tests
* Optionally rewrite some members using functions already existing in FsToolkit.ErrorHandling, making sure tests still pass

**Comment by TheAngryByrd** [comment]
Sounds like a plan.  I'll get to it this week.

**Comment by demystifyfp** [comment]
Thanks, @TheAngryByrd for the changes. Is anything else pending? Can I release a beta version to test things out? 

@cmeeren Are you available test this new one after I release this new version?

**Comment by cmeeren** [comment]
Sure, but if you want I can check out the PR branch and test before you merge/release. (With "test", I mean run the suite of unit tests in Cvdm.ErrorHandling.)

I'll try to do it today.

**Comment by cmeeren** [comment]
Good to go; all existing Cvdm.ErrorHandling tests pass using `TheAngryByrd:more-CE-binds`.

(Except the `requireEqual` and `requireEqualTo` tests, because these haven't been merged yet, see https://github.com/demystifyfp/FsToolkit.ErrorHandling/issues/3#issuecomment-461419881)

**Comment by demystifyfp** [comment]
Thanks, @cmeeren for testing these changes. @TheAngryByrd Can I merge it?

**Comment by TheAngryByrd** [comment]
Merge it! 👍

**Comment by cmeeren** [comment]
:shipit:

**Comment by demystifyfp** [comment]
@TheAngryByrd @cmeeren I am facing some weird issues with the FSharp 4.6 update on my machine, and I am unable to publish the package because of this. I will release the new version as soon as I resolved this.

**Pull request merged**
