### PR TITLE
issue-78-async-seq

### PR DESCRIPTION
**Pull request by njlr**

### CODE REVIEW

**Comment by TheAngryByrd** [comment]
Thanks a ton!!!

**Comment by TheAngryByrd** [comment]
@njlr would you mind adding `theangrybyrd` and `demystifyfp` to the owners of the `FsToolkit.ErrorHandling.AsyncSeq` package so I release it?  Thanks!

**Comment by njlr** [comment]
> @njlr would you mind adding `theangrybyrd` and `demystifyfp` to the owners of the `FsToolkit.ErrorHandling.AsyncSeq` package so I can release it? Thanks!

Done.

**Comment by TheAngryByrd** [comment]
Could you check again?

```

Paket failed with
-> RequestFailedException: Request to 'https://www.nuget.org/api/v2/package' failed with: 403 Forbidden — The specified API key is invalid, has expired, or does not have permission to access the specified package.The specified API key is invalid, has expired, or does not have permission to access the specified package.
```

**Comment by TheAngryByrd** [comment]
Nevermind, had to navigate nuget's UI since I didn't get an email from them about it.  Thanks again for this!

**Comment by njlr** [comment]
Great to see it published! 

Once everything is settled please can you remove me from the package? I think I'm just a liability!

**Comment by TheAngryByrd** [comment]
Released in 2.11.0 since I forgot to link this PR in the release notes

**Pull request merged**
