### PR TITLE
TaskResult

### PR DESCRIPTION
**Pull request by TheAngryByrd**
Part of #17 

Currently implements all of the `TaskResult` functions similar to `AsyncResult`.

Implements all of the `CE` except `While` and `For` because the naive implementation causes stackoverflows.  I'll need help from @rspeele or @@NinoFloris because it's a bit beyond my current understanding.

### CODE REVIEW

**Comment by baronfel** [comment]
To debug the stackoverflow you should add a 'Quote' member to the builder. That'll make any use of the builder an expression for the chain of calls that would have been run, and if you print that you can see the transformations

**Comment by TheAngryByrd** [comment]
Ok, utilizes more of the internals of `TaskBuilder.fs` to to allow for While/For loops.

**Comment by cmeeren** [comment]
> more of the internals

Wouldn't it be prudent to utilize pretty much all of the internals?

I may be wrong, but AFAIK there's a bit of nuanced implementation details in TaskBuilder.fs to make everything work correctly/optimally.

**Comment by TheAngryByrd** [comment]
It can't use all of them, they're tied pretty heavily to the `Step`'s type being `unit`.  Compare signature of the [`whileLoopR`](https://github.com/demystifyfp/FsToolkit.ErrorHandling/pull/18/files#diff-00e8e3c175344a2c041e566332a7826fR21) vs the [`whileLoop`](https://github.com/rspeele/TaskBuilder.fs/blob/master/TaskBuilder.fs#L145) in TaskBuilder.

**Comment by demystifyfp** [comment]
@TheAngryByrd I added you as a collaborator for this repository, and I guess you should have permission to merge the pull requests. 

Do you have plans to update the documentation and the build script as part of this issue?

**Comment by TheAngryByrd** [comment]
Oh of course I should.  This is why I like having reviews, help me catch things I didn't think about.

**Comment by TheAngryByrd** [comment]
@demystifyfp this is ready for a final review.

**Comment by demystifyfp** [comment]
Thanks, @TheAngryByrd, Will do it on the weekend.

**Comment by demystifyfp** [comment]
@TheAngryByrd There are few minor fixes, and I have fixed it. You can update your branch by applying the patch files in the attached [Patches.zip](https://github.com/demystifyfp/FsToolkit.ErrorHandling/files/3124853/Patches.zip) file. 

Have you considered "TaskResultOption" ?

**Comment by TheAngryByrd** [comment]
Just for future reference you can either submit a PR to my PR or you can [edit this PR directly](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork)

**Comment by TheAngryByrd** [comment]
For `TaskResultOption`, the CE will be a lot of the same work as `TaskResultCE`.  I figured getting out just `TaskResult` first would be optimal.

**Comment by demystifyfp** [comment]
Thanks, @TheAngryByrd. I was not aware of that. Will merge and publish the package later today.

**Comment by TheAngryByrd** [comment]
Ping :)

**Comment by demystifyfp** [comment]
Hi @TheAngryByrd. I am out of town (some unplanned personal work) with no access to laptop and I will do it for sure over this weekend.

**Comment by demystifyfp** [comment]
@cmeeren & @TheAngryByrd I am facing the below error while trying to publish the package

```
/oss/FsToolkit.ErrorHandling/.paket/Paket.Restore.targets(356,5): error : Could not find a part of the path '/oss/FsToolkit.ErrorHandling/src/FsToolkit.ErrorHandling/obj/Release/FsToolkit.ErrorHandling.1.1.0.nuspec;
/oss/FsToolkit.ErrorHandling/src/FsToolkit.ErrorHandling/obj/Release'. 
[/oss/FsToolkit.ErrorHandling/src/FsToolkit.ErrorHandling/FsToolkit.ErrorHandling.fsproj]
PackTask: /oss/FsToolkit.ErrorHandling/.paket/Paket.Restore.targets(356,5): error : Could not find a part of the path '/oss/FsToolkit.ErrorHandling/src/FsToolkit.ErrorHandling/obj/Release/FsToolkit.ErrorHandling.1.1.0.nuspec;/oss/FsToolkit.ErrorHandling/src/FsToolkit.ErrorHandling/obj/Release'.
```

I remember facing this kind of some time back on a different project and that time removing the `obj` folder solved the issue. But this time, it is not working.

Any idea how to fix this?

**Comment by cmeeren** [comment]
Nope, never seen that error before, sorry.

**Comment by TheAngryByrd** [comment]
I haven't seen it before either. Probably worth posting on paket's issues

**Comment by demystifyfp** [comment]
@forki Can you help us here? 

We are getting an error that the ".nuspec" file not while trying to publish the package and here is the stack trace

```
/oss/FsToolkit.ErrorHandling/.paket/Paket.Restore.targets(356,5): error : Could not find a part of the path '/oss/FsToolkit.ErrorHandling/src/FsToolkit.ErrorHandling/obj/Release/FsToolkit.ErrorHandling.1.1.0.nuspec;
/oss/FsToolkit.ErrorHandling/src/FsToolkit.ErrorHandling/obj/Release'. 
[/oss/FsToolkit.ErrorHandling/src/FsToolkit.ErrorHandling/FsToolkit.ErrorHandling.fsproj]
PackTask: /oss/FsToolkit.ErrorHandling/.paket/Paket.Restore.targets(356,5): error : Could not find a part of the path '/oss/FsToolkit.ErrorHandling/src/FsToolkit.ErrorHandling/obj/Release/FsToolkit.ErrorHandling.1.1.0.nuspec;/oss/FsToolkit.ErrorHandling/src/FsToolkit.ErrorHandling/obj/Release'.
```

**Comment by TheAngryByrd** [comment]
It seems to be related to https://github.com/demystifyfp/FsToolkit.ErrorHandling/pull/21/files.  So something with the sourcelinking and paket aren't playing nice.

**Comment by TheAngryByrd** [comment]
Commenting out https://github.com/demystifyfp/FsToolkit.ErrorHandling/blob/master/src/FsToolkit.ErrorHandling/FsToolkit.ErrorHandling.fsproj#L6-L9 seems to make it pack again

**Comment by TheAngryByrd** [comment]
Looks like this is the same issue https://github.com/fsprojects/Paket/issues/3521

**Comment by baronfel** [comment]
You should be able to sidestep the issue by disabling symbol package generation and embedding your portable pdbs on the project file. See discussion here: https://github.com/dotnet/sdk/issues/2679. The downside is larger assembly size, but the upside is better tooling generation as mentioned in that issue.

**Comment by cmeeren** [comment]
Sounds like a win to me!

**Comment by TheAngryByrd** [comment]
According to https://github.com/dotnet/docs/pull/9110/files we could also specify `<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>` to add the pdbs to the nuget package if we didn't want them in the dlls for some reason.

**Comment by demystifyfp** [comment]
Thanks, @TheAngryByrd 

It worked!

https://www.nuget.org/packages/FsToolkit.ErrorHandling/1.1.0

https://www.nuget.org/packages/FsToolkit.ErrorHandling.TaskResult/1.1.0

**Comment by cmeeren** [comment]
In TaskBuilder.fs there are several variants of the `task` CE. For example one can `open FSharp.Control.Tasks.V2.ContextInsensitive` to get what I suppose is `ContinueAwait(false)` behaviour. How is `taskBuilder` implemented with respect to the `task` variants?

**Comment by TheAngryByrd** [comment]
I did the `ContextInsensitive` since I'm under the impression everyone should use [ConfigureAwait in library code](https://medium.com/bynder-tech/c-why-you-should-use-configureawait-false-in-your-library-code-d7837dce3d7f).

**Comment by cmeeren** [comment]
Exactly what I hoped to hear 👍 

By the way, I ran `taskResult` against all of the Cvdm.ErrorHandling `asyncResult` tests and everything looks good on that front.

**Pull request merged**
