### PR TITLE
Add Result.sequenceAsync

### PR DESCRIPTION
**Pull request by cmeeren**
Fixes #50 

I haven't added any tests because I can't think of anything to test that the compiler does not guarantee. AFAIK you'd have to use reflection in order to have a bug.

I also haven't added any doc comments to the function since the other `sequence` functions don't have that.

### CODE REVIEW

**Comment by TheAngryByrd** [comment]
The one test I can think of is it gives you the result you've passed in. Theoretically this function could just return unchecked defaultOf. I know it would be stupid but at least we have a real test.

**Comment by TheAngryByrd** [comment]
Could you also add implementations for Task and Job libraries?

**Comment by tamizhvendan** [comment]
Thanks, @cmeeren. Can you add the documentation as well?

**Comment by tamizhvendan** [comment]
Thanks, @cmeeren

**Pull request merged**
