### PR TITLE
Close issue #145 - add Result.traverseAsync

### PR DESCRIPTION
**Pull request by saerosV**
## Proposed Changes

From issue #145.

Adds a new `traverseAsync` function at `src/FsToolkit.ErrorHandling/Result.fs`, and its necessary tests at `tests/FsToolkit.ErrorHandling.Tests/Result.fs`.

Tests results:
tests
 

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] Build and tests pass locally
- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Further comments

The only thing left to do is to add a proper description to traverseAsync. Open to suggestions.

### CODE REVIEW

**Review by TheAngryByrd — CHANGES_REQUESTED** [review]
Thanks for this!

Build is failing. Looks like you need to run `./build.sh formatcode`.

**Comment by saerosV** [comment]
Hi @TheAngryByrd! After running `./build.sh formatcode`, the only file changed was `.paket/Paket.Restore.targets`.
More specifically, at line 162:
diff0
diff1

Would this make any difference? Not sure how to proceed otherwise. Thanks!

**Comment by TheAngryByrd** [comment]
> Hi @TheAngryByrd! After running `./build.sh formatcode`, the only file changed was `.paket/Paket.Restore.targets`. More specifically, at line 162: diff0 diff1
> 
> Would this make any difference? Not sure how to proceed otherwise. Thanks!

Hmm that sounds like FAKE is fighting Paket for that file.  Add `PAKET_SKIP_RESTORE_TARGETS=true` to the `build.sh` file.

**Comment by TheAngryByrd** [comment]
Hmm no changes to the source code but `CheckFormatCode` is failing.  Have you seen this before @nojaf?

**Comment by TheAngryByrd** [comment]
I'm wondering if this is some line ending shenanigans.

**Review by TheAngryByrd — APPROVED** [review]
Well dealing with build tool problems shouldn't be your problem @saerosV. Since this builds locally on my machine, I'm going to merge and see what happens with CI. Thanks for this!

**Comment by saerosV** [comment]
Adding `PAKET_SKIP_RESTORE_TARGETS=true` to `build.sh` solved the issue for me. I could still commit the formatted files, if that's better. Thank you for the help!

**Comment by nojaf** [comment]
@TheAngryByrd I'll take a look at this next week. Thanks for the tag!

**Comment by nojaf** [comment]
So, looking in more detail, I didn't find anything out of the ordinary.
Did @saerosV not commit the formatted files?
Line endings are ignored when you are using the `--check` flag.
`.editorconfig` `end_of_line` property is supported by Fantomas, I do recommend setting that one.

**Comment by TheAngryByrd** [comment]
Yeah it was weird, on saerosV branch I couldn't get formatting to work but after merging it did. Thanks for looking!

**Pull request merged**
